### ISSUE TITLE
No results returned from command line or example code

### ISSUE THREAD

**Issue by edmomot** [ryangreenberg/urban_dictionary#5]
I just ran gem install urban_dictionary and that completed successfully.

The machine is a virtual ubuntu image that's pretty vanilla.

Tried running the example code, and that spits out nothing.  No luck with the command line interface either.

### Command line results:

$ urban_dictionary QED
QED
\--------

### test_urbandictionary.rb contents:

require 'urban_dictionary'

word = UrbanDictionary.define("QED")
word.entries.size # => 7
word.entries.each do |entry|
  puts entry.definition
  puts entry.example
end

### Test code results: 
$ ruby test_urbandictionary.rb 
$

**Comment by ryangreenberg** [comment]
@edmomot Thanks for taking the time to report an issue. I apologize for the glacial response time. I just released a new version of the gem which handles Urban Dictionary's new layout and should solve your problem, in the remote case that you are still interested in getting the definition of QED using this gem.
